# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\"/\n\tModelInfo\x12\x12\n\x02id\x18\x01 \x01(\x0b\x32\x06.JobID\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"\"\n\x06Target\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\"&\n\x08Training\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x13\n\x05JobID\x12\n\n\x02id\x18\x01 \x01(\x03\"2\n\tTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x12\n\nmodel_info\x18\x02 \x01(\t\"f\n\x08Progress\x12\n\n\x02id\x18\x01 \x01(\x03\x12!\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x13.Progress.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x07Results\x12\x0e\n\x06target\x18\x01 \x01(\t\x12&\n\x07metrics\x18\x02 \x03(\x0b\x32\x15.Results.MetricsEntry\x1a<\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.Predictions:\x02\x38\x01\"\'\n\nAllResults\x12\x19\n\x07results\x18\x01 \x03(\x0b\x32\x08.Results\"\x87\x01\n\x0bPredictions\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\x12\x30\n\nevaluation\x18\x02 \x03(\x0b\x32\x1c.Predictions.EvaluationEntry\x1a\x31\n\x0f\x45valuationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\" \n\tInference\x12\x13\n\x0bpredictions\x18\x01 \x01(\x0c\x32\xe4\x01\n\nRouteGuide\x12(\n\rStartTraining\x12\n.ModelInfo\x1a\t.Training\"\x00\x12\"\n\x0bGetProgress\x12\x06.JobID\x1a\t.Progress\"\x00\x12/\n\x18GetSpecificTargetResults\x12\x07.Target\x1a\x08.Results\"\x00\x12-\n\x14GetAllTargetsResults\x12\x06.JobID\x1a\x0b.AllResults\"\x00\x12(\n\x0cGetInference\x12\n.Timestamp\x1a\n.Inference\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROGRESS_DATAENTRY._options = None
  _PROGRESS_DATAENTRY._serialized_options = b'8\001'
  _RESULTS_METRICSENTRY._options = None
  _RESULTS_METRICSENTRY._serialized_options = b'8\001'
  _PREDICTIONS_EVALUATIONENTRY._options = None
  _PREDICTIONS_EVALUATIONENTRY._serialized_options = b'8\001'
  _globals['_MODELINFO']._serialized_start=14
  _globals['_MODELINFO']._serialized_end=61
  _globals['_TARGET']._serialized_start=63
  _globals['_TARGET']._serialized_end=97
  _globals['_TRAINING']._serialized_start=99
  _globals['_TRAINING']._serialized_end=137
  _globals['_JOBID']._serialized_start=139
  _globals['_JOBID']._serialized_end=158
  _globals['_TIMESTAMP']._serialized_start=160
  _globals['_TIMESTAMP']._serialized_end=210
  _globals['_PROGRESS']._serialized_start=212
  _globals['_PROGRESS']._serialized_end=314
  _globals['_PROGRESS_DATAENTRY']._serialized_start=271
  _globals['_PROGRESS_DATAENTRY']._serialized_end=314
  _globals['_RESULTS']._serialized_start=316
  _globals['_RESULTS']._serialized_end=443
  _globals['_RESULTS_METRICSENTRY']._serialized_start=383
  _globals['_RESULTS_METRICSENTRY']._serialized_end=443
  _globals['_ALLRESULTS']._serialized_start=445
  _globals['_ALLRESULTS']._serialized_end=484
  _globals['_PREDICTIONS']._serialized_start=487
  _globals['_PREDICTIONS']._serialized_end=622
  _globals['_PREDICTIONS_EVALUATIONENTRY']._serialized_start=573
  _globals['_PREDICTIONS_EVALUATIONENTRY']._serialized_end=622
  _globals['_INFERENCE']._serialized_start=624
  _globals['_INFERENCE']._serialized_end=656
  _globals['_ROUTEGUIDE']._serialized_start=659
  _globals['_ROUTEGUIDE']._serialized_end=887
# @@protoc_insertion_point(module_scope)
